#!/system/bin/sh

source /res/synapse/config.general
mount -t rootfs -o rw,remount rootfs

if [ ! -e /res/synapse/settings ]; then
    $BB mkdir -p /res/synapse/settings
    $BB chmod -R 0755 /data/PRIME-Kernel
fi

function initial_prof() {
	if [ -f $1 ]; then
		prof_value=`cat $1`
		if [[ -z $prof_value ]] || [[ "$prof_value" == "null" ]]; then
    		echo $2 > $1
		fi
	else
		touch $1
   		echo $2 > $1
	fi
}

$BB mkdir -p /data/PRIME-Kernel/synapse/settings
initial_prof /res/synapse/settings/dvfs_disabler 1
initial_prof /res/synapse/settings/loader_unroot 1
initial_prof /data/PRIME-Kernel/synapse/settings/loader_unroot 1
initial_prof /res/synapse/settings/extsd_patch_00 1
initial_prof /res/synapse/settings/viper_patch_00 0
initial_prof /res/synapse/settings/gms_drain 0
initial_prof /res/synapse/settings/dcm_drain 0
initial_prof /res/synapse/settings/tweak_perf 0
initial_prof /res/synapse/settings/tweak_ram 0
initial_prof /res/synapse/settings/tweak_net 0
initial_prof /res/synapse/settings/tweak_touch 0
initial_prof /res/synapse/settings/profile none
initial_prof /res/synapse/settings/vnswap0 1
initial_prof /data/PRIME-Kernel/synapse/settings/bbins_xbin 0
initial_prof /data/PRIME-Kernel/synapse/settings/bbins_last 0
initial_prof /res/synapse/settings/synapse_do_not_clear 0
initial_prof /res/synapse/settings/cpu0_max 1300000
initial_prof /res/synapse/settings/cpu4_max 1800000

if [ ! -f $CONFIG_JSON ]; then
	source $PRIME/config.json.generate > $CONFIG_JSON
fi

case "${1}" in
  config)
	cat $CONFIG_JSON;;
  configpath)
	echo $CONFIG_JSON;;
  actionpath)
	echo $ACTION_SCRIPTS;;
  reset)
   rm -f $PRIME/config.json;
esac;
