#!/system/bin/sh

BB=/res/bin/busybox;
alias bb=/res/bin/busybox;
cpufreq0="/sys/devices/system/cpu/cpu0/cpufreq"
cpufreq4="/sys/devices/system/cpu/cpu4/cpufreq"
G0="$cpufreq0/scaling_governor"
G4="$cpufreq4/scaling_governor"

if [ -f $1 ];then
	OLD=`cat $1`
	if [[ ! -z $2 ]]; then
	  NEW=$2
	  if [ $OLD != $NEW ]; then
	    if [ $NEW == "interactive" ] || [ $NEW == "cafactive" ]; then
			echo $NEW > $G0
			bb usleep 500000
			echo 19000 > $cpufreq0/$NEW/above_hispeed_delay
			echo 0 > $cpufreq0/$NEW/boost
			echo 40000 > $cpufreq0/$NEW/boostpulse_duration
			echo 85 > $cpufreq0/$NEW/go_hispeed_load
			echo 900000 > $cpufreq0/$NEW/hispeed_freq
			echo 1 > $cpufreq0/$NEW/io_is_busy
			echo 40000 > $cpufreq0/$NEW/min_sample_time
			echo 75 > $cpufreq0/$NEW/target_loads
			echo 20000 > $cpufreq0/$NEW/timer_rate
			echo 20000 > $cpufreq0/$NEW/timer_slack
			[ $NEW == "cafactive" ] && echo 0 > $cpufreq0/$NEW/max_freq_hysteresis

			echo $NEW > $G4
			bb usleep 500000
			echo 59000 1200000:119000 1700000:19000 > $cpufreq4/$NEW/above_hispeed_delay
			echo 0 > $cpufreq4/$NEW/boost
			echo 40000 > $cpufreq4/$NEW/boostpulse_duration
			echo 85 > $cpufreq4/$NEW/go_hispeed_load
			echo 1000000 > $cpufreq4/$NEW/hispeed_freq
			echo 1 > $cpufreq4/$NEW/io_is_busy
			echo 99000 > $cpufreq4/$NEW/min_sample_time
			echo 60 1300000:63 1500000:65 190000:70 > $cpufreq4/$NEW/target_loads
			echo 20000 > $cpufreq4/$NEW/timer_rate
			echo 20000 > $cpufreq4/$NEW/timer_slack
			[ $NEW == "cafactive" ] && echo 0 > $cpufreq4/$NEW/max_freq_hysteresis

	    else
		    echo $NEW > $1
			bb usleep 500000
	    fi
	  fi
    fi
	sync
    echo `cat $1`
fi
