#!/system/bin/sh

alias bb=/res/bin/busybox;
BB=/res/bin/busybox;
INC=/data/PRIME-Kernel/bin/xposed.inc
PRIME=/data/PRIME-Kernel

case $1 in
donotclear)
    P=/res/synapse/settings/synapse_do_not_clear
    if [ ! -f $P ]; then
        echo 0 > $P
    fi
    if [ ! -z $2 ]; then
        if [ $2 -eq 1 ]; then
            touch /sdcard/Synapse/.do_not_remove_data
            echo 1 > $P
            echo 1
        else
            rm /sdcard/Synapse/.do_not_remove_data > /dev/null 2>&1
            echo 0 > $P
            echo 0
        fi
    else
        echo $(cat $P)
    fi
    ;;

/res/synapse/settings/gms_drain)
	if [ ! -z $2 ]; then
		echo $2 > $1
		VAR=$(cat $1)
		if [ $VAR -eq 1 ]; then
			(while :
			do
				pid=$(bb pidof com.google.android.gms)
				if [ ! -z $pid ]; then
					sleep 1
					kill $pid 2> /dev/null;
					pm enable com.google.android.gms/.update.SystemUpdateActivity > /dev/null 2>&1;
					pm enable com.google.android.gms/.update.SystemUpdateService > /dev/null 2>&1;
					pm enable com.google.android.gms/.update.SystemUpdateService$ActiveReceiver > /dev/null 2>&1;
					pm enable com.google.android.gms/.update.SystemUpdateService$Receiver > /dev/null 2>&1;
					pm enable com.google.android.gms/.update.SystemUpdateService$SecretCodeReceiver > /dev/null 2>&1;
					pm enable com.google.android.gsf/.update.SystemUpdateActivity > /dev/null 2>&1;
					pm enable com.google.android.gsf/.update.SystemUpdatePanoActivity > /dev/null 2>&1;
					pm enable com.google.android.gsf/.update.SystemUpdateService > /dev/null 2>&1;
					pm enable com.google.android.gsf/.update.SystemUpdateService$Receiver > /dev/null 2>&1;
					pm enable com.google.android.gsf/.update.SystemUpdateService$SecretCodeReceiver > /dev/null 2>&1;
					break;
				else
					sleep 1
				fi
			done
			) &
		fi
	fi
	echo $(cat $1)
;;

/res/synapse/settings/dcm_drain)
	if [ ! -z $2 ]; then
		echo $2 > $1
		VAR=$(cat $1)
		if [ $VAR -eq 1 ]; then
			pm disable com.samsung.dcm > /dev/null 2>&1;
		else
			pm enable com.samsung.dcm > /dev/null 2>&1;
		fi
	fi
	echo $(cat $1)
;;
esac
