#!/system/bin/sh

BB=/res/bin/busybox;
INC=/data/PRIME-Kernel/bin/modules.inc

if [ -e $INC ]; then
	echo 1 > /res/test.dat
	ERR=$?
	if [ $ERR -ne 0 ]; then
		$BB mount -t rootfs -o remount,rw rootfs
	else
		rm /res/test.dat 2>/dev/null
	fi
    source $INC
else
	echo "0";
fi
